--Susan Fayez
--001404420
--fayezs


CONNECT TO SE3DB3;


--q1
SELECT PID, NAME FROM PERSONS WHERE PID IN(
SELECT PID FROM PARTICIP
GROUP BY PID
HAVING count(*) = 1);


--q2
SELECT PID, NAME FROM PERSONS WHERE PID IN(
SELECT PID FROM PARTICIP
GROUP BY PID
HAVING count(*) > 1);


--q3
SELECT p.PID, p.NAME, a.CITY FROM PERSONS p
JOIN HASA h
ON p.PID = h.PID
JOIN ADDRESSES a
ON h.addrID = a.addrID
ORDER BY a.CITY;


--q4
SELECT PID, NAME FROM PERSONS WHERE PID IN (
SELECT PID FROM HASCO WHERE TID IN (
SELECT TID FROM ITINERARIES WHERE Year(DATE) = 2015))
AND PID IN (
SELECT PID FROM CUSTOMERS);


--q5
SELECT AGE, GENDER FROM PERSONS WHERE PID IN(
SELECT PID FROM HASE WHERE PID IN(
SELECT PID FROM EMPLOYEES));


--q6
SELECT PROVID FROM ISP WHERE PROVID NOT IN (
SELECT PROVID FROM ISP WHERE SVCTYPE = 'ACCOM');


--q7
SELECT PROVID FROM ISP WHERE PROVID NOT IN (
SELECT PROVID FROM ISP WHERE SVCTYPE = 'ACCOM')
OR PROVID NOT IN (
SELECT PROVID FROM ISP WHERE SVCTYPE = 'MEAL');



--q8
SELECT PROVID, SVCTYPE FROM ISP WHERE PENALTY = 100.00 OR PENALTY = 200.00;


--q9
SELECT h.PID, p.NAME, c.counter AS numTours
FROM  HASCO h
INNER JOIN (SELECT PID, count(PID) as counter
FROM HASCO 
GROUP BY PID)
c ON h.PID = c.PID
JOIN PERSONS p
ON h.PID = p.PID
ORDER BY h.AMOUNT DESC;


--q10
SELECT TID FROM TOURS WHERE TID IN(
SELECT TID FROM HASCO WHERE AMOUNT >= 5000.00)
AND (STATUS = 'I' OR STATUS = 'F');



TERMINATE;